console.log("Hello World From TypeScript")
console.log("Hello World From TypeScript")
console.log("Hello World From TypeScript")
console.log("Hello World From TypeScript")
console.log("Hello World From TypeScript")
console.log("Hello World From TypeScript")
console.log("Hello World From TypeScript")
console.log("Hellod")
